//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public string UserID { get; set; }
        public string FriendID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Friend Friend { get; set; }
    }
}
